spring:
  neo4j:
    authentication:
      username: neo4j
      password: wenjin-study
    uri: bolt://localhost:7687
#spring:
#  neo4j:
#    authentication:
#      username: neo4j
#      password: sunline
#    uri: bolt://10.22.1.110:7687

